-- =====================================================
-- SQL LEGADO NEUTRALIZADO — FORUM
-- =====================================================
--
-- Este arquivo era um schema solto do forum e foi mantido apenas
-- como marcador historico/preventivo para evitar execucao acidental.
--
-- Nao execute este arquivo para criar ou atualizar banco.
-- Nao use este arquivo como fonte da verdade do schema.
--
-- Fonte oficial do schema:
--   supabase/migrations/20260509100000_add_forum_schema.sql
--   supabase/migrations/20260509100300_use_profile_role_for_forum_admin.sql
--   supabase/migrations/20260509143000_create_forum_topic_people.sql
--
-- Documentacao relacionada:
--   docs/historico/SQLS_LEGADOS.md
--   docs/operacao/MIGRATIONS_SUPABASE.md
--   docs/funcionalidades/FORUM.md
--
-- Se algum trecho antigo deste arquivo parecer necessario, recupere-o
-- pelo historico do Git, compare com as migrations oficiais e crie uma
-- nova migration idempotente apenas para a diferenca real.
--
-- Este arquivo nao deve conter CREATE TABLE, CREATE POLICY, CREATE FUNCTION,
-- ALTER TABLE, INSERT ou qualquer instrucao operacional.
-- =====================================================
