-- =====================================================
-- SQL LEGADO NEUTRALIZADO — GOOGLE CALENDAR
-- =====================================================
--
-- Este arquivo era um schema solto da integracao Google Calendar e foi
-- mantido apenas como marcador historico/preventivo para evitar execucao
-- acidental.
--
-- Nao execute este arquivo para criar ou atualizar banco.
-- Nao use este arquivo como fonte da verdade do schema.
--
-- Fonte oficial do schema:
--   supabase/migrations/20260509100100_add_google_calendar_schema.sql
--
-- Documentacao relacionada:
--   docs/historico/SQLS_LEGADOS.md
--   docs/operacao/MIGRATIONS_SUPABASE.md
--   docs/operacao/OAUTH_GOOGLE.md
--
-- Se algum trecho antigo deste arquivo parecer necessario, recupere-o
-- pelo historico do Git, compare com a migration oficial e crie uma nova
-- migration idempotente apenas para a diferenca real.
--
-- Este arquivo nao deve conter CREATE TABLE, CREATE POLICY, CREATE FUNCTION,
-- ALTER TABLE, INSERT ou qualquer instrucao operacional.
-- =====================================================
