export type TreeColorPalette = 'white' | 'orange' | 'brown' | 'visual';

export const TREE_COLOR_PALETTE_STORAGE_KEY = 'arvorefamilia.treeColorPalette';

export const TREE_COLOR_PALETTE_CSS_VARIABLES = [
  '--tree-palette-canvas-bg',
  '--tree-palette-card-tataravos',
  '--tree-palette-card-bisavos',
  '--tree-palette-card-avos',
  '--tree-palette-card-tios',
  '--tree-palette-card-primos',
  '--tree-palette-card-pais',
  '--tree-palette-card-central',
  '--tree-palette-card-irmaos',
  '--tree-palette-card-sobrinhos',
  '--tree-palette-card-netos',
  '--tree-palette-card-pets',
  '--tree-palette-border-tataravos',
  '--tree-palette-border-bisavos',
  '--tree-palette-border-avos',
  '--tree-palette-border-tios',
  '--tree-palette-border-primos',
  '--tree-palette-border-pais',
  '--tree-palette-border-central',
  '--tree-palette-border-irmaos',
  '--tree-palette-border-sobrinhos',
  '--tree-palette-border-netos',
  '--tree-palette-border-pets',
  '--tree-palette-text-primary',
  '--tree-palette-text-muted',
  '--tree-palette-status-alive',
  '--tree-palette-status-deceased',
  '--tree-palette-card-border-pet',
  '--tree-palette-edge-spouse',
  '--tree-palette-edge-child',
  '--tree-palette-edge-sibling',
  '--tree-palette-group-bg',
  '--tree-palette-group-border',
  '--tree-palette-group-border-width',
  '--tree-palette-legend-bg',
] as const;

type TreeColorPaletteCssVariable = typeof TREE_COLOR_PALETTE_CSS_VARIABLES[number];

interface TreeColorPaletteDefinition {
  label: string;
  ariaLabel: string;
  swatch: string;
  swatchBorder: string;
  cssVariables: Record<TreeColorPaletteCssVariable, string>;
}

const whitePaletteVariables: Record<TreeColorPaletteCssVariable, string> = {
  '--tree-palette-canvas-bg': '#FFFFFF',
  '--tree-palette-card-tataravos': '#B7AED6',
  '--tree-palette-card-bisavos': '#D49BC5',
  '--tree-palette-card-avos': '#E8A29B',
  '--tree-palette-card-tios': '#EAB08F',
  '--tree-palette-card-primos': '#E7B985',
  '--tree-palette-card-pais': '#E4C37A',
  '--tree-palette-card-central': '#E7E8E8',
  '--tree-palette-card-irmaos': '#A9CB72',
  '--tree-palette-card-sobrinhos': '#B8CEC2',
  '--tree-palette-card-netos': '#BDD8DC',
  '--tree-palette-card-pets': '#F4C7AB',
  '--tree-palette-border-tataravos': '#B7AED6',
  '--tree-palette-border-bisavos': '#D49BC5',
  '--tree-palette-border-avos': '#E8A29B',
  '--tree-palette-border-tios': '#EAB08F',
  '--tree-palette-border-primos': '#E7B985',
  '--tree-palette-border-pais': '#E4C37A',
  '--tree-palette-border-central': '#E7E8E8',
  '--tree-palette-border-irmaos': '#A9CB72',
  '--tree-palette-border-sobrinhos': '#B8CEC2',
  '--tree-palette-border-netos': '#BDD8DC',
  '--tree-palette-border-pets': '#F4C7AB',
  '--tree-palette-text-primary': '#111827',
  '--tree-palette-text-muted': '#4B5563',
  '--tree-palette-status-alive': '#3F7F72',
  '--tree-palette-status-deceased': '#6B7280',
  '--tree-palette-card-border-pet': '#f59e0b',
  '--tree-palette-edge-spouse': '#EA580C',
  '--tree-palette-edge-child': '#CA8A04',
  '--tree-palette-edge-sibling': '#2563EB',
  '--tree-palette-group-bg': 'rgba(255, 255, 255, 0.04)',
  '--tree-palette-group-border': '#CBD5E1',
  '--tree-palette-group-border-width': '3px',
  '--tree-palette-legend-bg': 'rgba(255, 255, 255, 0.9)',
};

const orangePaletteVariables: Record<TreeColorPaletteCssVariable, string> = {
  '--tree-palette-canvas-bg': '#FFF1E3',
  '--tree-palette-card-tataravos': 'linear-gradient(135deg, #F6C97A 0%, #EE9A72 100%)',
  '--tree-palette-card-bisavos': 'linear-gradient(135deg, #F2B35D 0%, #EE9A72 100%)',
  '--tree-palette-card-avos': 'linear-gradient(135deg, #F8C28E 0%, #E8783E 100%)',
  '--tree-palette-card-tios': 'linear-gradient(135deg, #F6C97A 0%, #D8844F 100%)',
  '--tree-palette-card-primos': 'linear-gradient(135deg, #FFD79A 0%, #F2B35D 100%)',
  '--tree-palette-card-pais': 'linear-gradient(135deg, #F2B35D 0%, #D8844F 100%)',
  '--tree-palette-card-central': 'linear-gradient(160deg, #E8783E 0%, #C95F35 100%)',
  '--tree-palette-card-irmaos': 'linear-gradient(135deg, #C4D983 0%, #A8C76B 100%)',
  '--tree-palette-card-sobrinhos': 'linear-gradient(135deg, #FFE1BA 0%, #EE9A72 100%)',
  '--tree-palette-card-netos': 'linear-gradient(135deg, #FFF8EF 0%, #F6C97A 100%)',
  '--tree-palette-card-pets': 'linear-gradient(135deg, #F8C28E 0%, #E8783E 100%)',
  '--tree-palette-border-tataravos': '#EE9A72',
  '--tree-palette-border-bisavos': '#E8783E',
  '--tree-palette-border-avos': '#D8844F',
  '--tree-palette-border-tios': '#D8844F',
  '--tree-palette-border-primos': '#F2B35D',
  '--tree-palette-border-pais': '#C95F35',
  '--tree-palette-border-central': '#C95F35',
  '--tree-palette-border-irmaos': '#A8C76B',
  '--tree-palette-border-sobrinhos': '#EE9A72',
  '--tree-palette-border-netos': '#F2B35D',
  '--tree-palette-border-pets': '#E8783E',
  '--tree-palette-text-primary': '#2F241D',
  '--tree-palette-text-muted': '#7A4A2B',
  '--tree-palette-status-alive': '#6D8C3E',
  '--tree-palette-status-deceased': '#9B6B4A',
  '--tree-palette-card-border-pet': '#E8783E',
  '--tree-palette-edge-spouse': '#C95F35',
  '--tree-palette-edge-child': '#E1A06E',
  '--tree-palette-edge-sibling': '#D8844F',
  '--tree-palette-group-bg': '#FFF8EF',
  '--tree-palette-group-border': '#E1A06E',
  '--tree-palette-group-border-width': '3px',
  '--tree-palette-legend-bg': 'rgba(255, 248, 239, 0.96)',
};

const brownPaletteVariables: Record<TreeColorPaletteCssVariable, string> = {
  '--tree-palette-canvas-bg': '#F4EFE6',
  '--tree-palette-card-tataravos': 'linear-gradient(135deg, #F4EFE6, #D9C7AD)',
  '--tree-palette-card-bisavos': 'linear-gradient(135deg, #FBF8F1, #E0CCB0)',
  '--tree-palette-card-avos': 'linear-gradient(135deg, #EADCC8, #D2B48F)',
  '--tree-palette-card-tios': 'linear-gradient(135deg, #E7D8BF, #C9906F)',
  '--tree-palette-card-primos': 'linear-gradient(135deg, #F4EFE6, #D9B08C)',
  '--tree-palette-card-pais': 'linear-gradient(135deg, #E2D2BA, #A85F45)',
  '--tree-palette-card-central': 'linear-gradient(135deg, #A85F45, #66745B)',
  '--tree-palette-card-irmaos': 'linear-gradient(135deg, #D9C7AD, #66745B)',
  '--tree-palette-card-sobrinhos': 'linear-gradient(135deg, #E7D8BF, #9AA082)',
  '--tree-palette-card-netos': 'linear-gradient(135deg, #F4EFE6, #B9B99A)',
  '--tree-palette-card-pets': 'linear-gradient(135deg, #EADCC8, #A85F45)',
  '--tree-palette-border-tataravos': '#CBBDA6',
  '--tree-palette-border-bisavos': '#CBBDA6',
  '--tree-palette-border-avos': '#A9825A',
  '--tree-palette-border-tios': '#A85F45',
  '--tree-palette-border-primos': '#A85F45',
  '--tree-palette-border-pais': '#8B5E34',
  '--tree-palette-border-central': '#5B4636',
  '--tree-palette-border-irmaos': '#66745B',
  '--tree-palette-border-sobrinhos': '#66745B',
  '--tree-palette-border-netos': '#66745B',
  '--tree-palette-border-pets': '#8B5E34',
  '--tree-palette-text-primary': '#2F2A25',
  '--tree-palette-text-muted': '#5B4636',
  '--tree-palette-status-alive': '#66745B',
  '--tree-palette-status-deceased': '#A9825A',
  '--tree-palette-card-border-pet': '#A85F45',
  '--tree-palette-edge-spouse': '#A85F45',
  '--tree-palette-edge-child': '#66745B',
  '--tree-palette-edge-sibling': '#8B5E34',
  '--tree-palette-group-bg': '#F4EFE6',
  '--tree-palette-group-border': '#CBBDA6',
  '--tree-palette-group-border-width': '2px',
  '--tree-palette-legend-bg': 'rgba(251, 248, 241, 0.94)',
};

export const TREE_COLOR_PALETTES: Record<TreeColorPalette, TreeColorPaletteDefinition> = {
  white: {
    label: 'Padrão',
    ariaLabel: 'Usar paleta padrão branca',
    swatch: '#FFFFFF',
    swatchBorder: '#CBD5E1',
    cssVariables: whitePaletteVariables,
  },
  orange: {
    label: 'Laranja',
    ariaLabel: 'Usar paleta laranja',
    swatch: '#E8783E',
    swatchBorder: '#C95F35',
    cssVariables: orangePaletteVariables,
  },
  brown: {
    label: 'Marrom',
    ariaLabel: 'Usar paleta marrom premium',
    swatch: '#8B5E34',
    swatchBorder: '#5B4636',
    cssVariables: brownPaletteVariables,
  },
  visual: {
    label: 'Visual',
    ariaLabel: 'Usar paleta visual azul e ciano',
    swatch: '#0891B2',
    swatchBorder: '#0E7490',
    cssVariables: {
      '--tree-palette-canvas-bg': '#ECFEFF',
      '--tree-palette-card-tataravos': '#CCFBF1',
      '--tree-palette-card-bisavos': '#99F6E4',
      '--tree-palette-card-avos': '#67E8F9',
      '--tree-palette-card-tios': '#A5F3FC',
      '--tree-palette-card-primos': '#CFFAFE',
      '--tree-palette-card-pais': '#5EEAD4',
      '--tree-palette-card-central': '#38BDF8',
      '--tree-palette-card-irmaos': '#99F6E4',
      '--tree-palette-card-sobrinhos': '#CFFAFE',
      '--tree-palette-card-netos': '#BAE6FD',
      '--tree-palette-card-pets': '#A7F3D0',
      '--tree-palette-border-tataravos': '#0F766E',
      '--tree-palette-border-bisavos': '#0D9488',
      '--tree-palette-border-avos': '#0891B2',
      '--tree-palette-border-tios': '#0891B2',
      '--tree-palette-border-primos': '#06B6D4',
      '--tree-palette-border-pais': '#0F766E',
      '--tree-palette-border-central': '#0369A1',
      '--tree-palette-border-irmaos': '#0D9488',
      '--tree-palette-border-sobrinhos': '#0891B2',
      '--tree-palette-border-netos': '#0284C7',
      '--tree-palette-border-pets': '#0D9488',
      '--tree-palette-text-primary': '#0F172A',
      '--tree-palette-text-muted': '#334155',
      '--tree-palette-status-alive': '#0F766E',
      '--tree-palette-status-deceased': '#64748B',
      '--tree-palette-card-border-pet': '#0D9488',
      '--tree-palette-edge-spouse': '#0891B2',
      '--tree-palette-edge-child': '#0E7490',
      '--tree-palette-edge-sibling': '#0284C7',
      '--tree-palette-group-bg': '#FFFFFF',
      '--tree-palette-group-border': '#0891B2',
      '--tree-palette-group-border-width': '2px',
      '--tree-palette-legend-bg': 'rgba(255, 255, 255, 0.94)',
    },
  },
} as const;

export function isTreeColorPalette(value: unknown): value is TreeColorPalette {
  return value === 'white' || value === 'orange' || value === 'brown' || value === 'visual';
}
