import { Edge, Node } from 'reactflow';
import { Relacionamento } from '../../../types';
import { isHumanFamilyMember, isPetFamilyMember } from '../../../utils/personEntity';
import {
  DEFAULT_DIRECT_RELATIVE_FILTERS,
  DirectRelationVariant,
  DirectRelativeFilters,
  EdgeFilters,
  TreeLayoutBounds,
  TreeLayoutParams,
  TreeLayoutResult,
  VisualLineFilters,
  getSortableBirthValue,
} from '../types';
import { DIRECT_FAMILY_TOKENS, FAMILY_TREE_COLORS } from '../visualTokens';

interface DirectFamilyLayoutOptions {
  centralPersonId?: string;
  filters?: DirectRelativeFilters;
  visiblePersonIds?: Set<string>;
  visualLineFilters?: VisualLineFilters;
  edgeFilters?: EdgeFilters;
  isMobile?: boolean;
}

type ParentKind = 'pai' | 'mae' | 'parent';
type DirectSide = 'paternal' | 'maternal';
type DirectLineGroup = 'spouse' | 'parentChild' | 'sibling' | 'auxiliary';

interface ParentLink {
  parentId: string;
  childId: string;
  kind: ParentKind;
}

interface RelationshipIndex {
  parentsByChild: Map<string, ParentLink[]>;
  childrenByParent: Map<string, Set<string>>;
  siblingsByPerson: Map<string, Set<string>>;
  spousesByPerson: Map<string, Set<string>>;
}

interface GroupSpec {
  key: string;
  label: string;
  ids: string[];
  variant: DirectRelationVariant;
  maxPerRow: number;
  centerX: number;
  side?: DirectSide;
  laneWidth?: number;
  fillAvailableWidth?: boolean;
  cardWidth?: number;
  cardHeight?: number;
  columnGap?: number;
  rowGap?: number;
  alignBoundary?: {
    side: 'left' | 'right';
    x: number;
  };
}

interface GroupBoxBounds {
  minX: number;
  minY: number;
  maxX: number;
  maxY: number;
  centerX: number;
  centerY: number;
}

interface GroupLayoutUnit {
  ids: string[];
}

interface GroupGridMetrics {
  rows: GroupLayoutUnit[][];
  largestRow: number;
  columns: number;
  cardsHeight: number;
  cardsWidth: number;
}

interface SideStackPlanItem {
  group: GroupSpec;
  topY: number;
  height: number;
}

const DIRECT_FRAME_EXTRA_HORIZONTAL_SPACE = 560;
const DIRECT_FRAME_LEFT = 10 - DIRECT_FRAME_EXTRA_HORIZONTAL_SPACE;
const DIRECT_FRAME_RIGHT = 3210 + DIRECT_FRAME_EXTRA_HORIZONTAL_SPACE;
const FRAME_TOP = 10;
const FRAME_BOTTOM = 1810;
const MOBILE_FRAME_LEFT = -70;
const MOBILE_FRAME_RIGHT = 3290;
const MOBILE_FRAME_TOP = -30;
const MOBILE_FRAME_BOTTOM = 2230;
const TITLE_TOP = FRAME_TOP + 10;
const TITLE_WIDTH = 1540;
const TITLE_RESERVED_HEIGHT = 80;
const VIEW_CENTER_X = (DIRECT_FRAME_LEFT + DIRECT_FRAME_RIGHT) / 2;
const VIEW_CENTER_Y = (FRAME_TOP + FRAME_BOTTOM) / 2;

const CARD_WIDTH = 400;
const CARD_HEIGHT = DIRECT_FAMILY_TOKENS.CARD_HEIGHT;
const CENTRAL_WIDTH = DIRECT_FAMILY_TOKENS.CENTRAL_WIDTH;
const CENTRAL_HEIGHT = 760;
const LEGEND_WIDTH = Math.min(760, CENTRAL_WIDTH * 1.8);
const LEGEND_HEIGHT = 92;
const LEGEND_BOTTOM_GAP = 30;

const SIDE_GROUPS_TOP = 170;
const SIDE_GROUPS_BOTTOM = FRAME_BOTTOM;
const CENTRAL_GROUP_TOP = SIDE_GROUPS_TOP;
const DIRECT_FILTER_PANEL_BOTTOM_ALIGNMENT_Y = SIDE_GROUPS_BOTTOM;
// Extra logical room used only by Minha Árvore so lower groups reach the filter panel's visual base.
const DIRECT_GROUPS_BOTTOM_ALIGNMENT_OFFSET = 600;
const DIRECT_GROUPS_BOTTOM_ALIGNMENT_Y =
  DIRECT_FILTER_PANEL_BOTTOM_ALIGNMENT_Y + DIRECT_GROUPS_BOTTOM_ALIGNMENT_OFFSET;
const CENTRAL_GROUP_BOTTOM = DIRECT_GROUPS_BOTTOM_ALIGNMENT_Y;

const GROUP_BOX_PADDING_X = 18;
const GROUP_BOX_PADDING_Y = 14;
const LABEL_HEIGHT = 38;
const LABEL_TO_CARD_GAP = 8;
const COLUMN_GAP = 14;
const ROW_GAP = 16;
const ROW_STEP = CARD_HEIGHT + ROW_GAP;
const SIDE_TOP = SIDE_GROUPS_TOP;
const SIDE_BOTTOM = SIDE_GROUPS_BOTTOM;
const SIDE_GROUP_MIN_GAP = 10;
const CENTRAL_X = VIEW_CENTER_X - CENTRAL_WIDTH / 2;
const CENTRAL_AREA_VERTICAL_CENTER_Y = (SIDE_GROUPS_TOP + DIRECT_GROUPS_BOTTOM_ALIGNMENT_Y) / 2;
const CENTRAL_LOWER_REFERENCE_HEIGHT = 620;
const CENTRAL_AREA_SHIFT_DOWN = 60;
const CENTRAL_BASE_Y = CENTRAL_AREA_VERTICAL_CENTER_Y - CENTRAL_LOWER_REFERENCE_HEIGHT / 2 + CENTRAL_AREA_SHIFT_DOWN;
const CENTRAL_CORE_SHIFT_UP = 180;
const CENTRAL_Y = CENTRAL_BASE_Y - CENTRAL_CORE_SHIFT_UP;
const CENTRAL_PARENT_GAP = 120;
const CENTRAL_LOWER_GROUP_GAP = 120;
const CENTRAL_LOWER_STACK_GAP = 34;
const CENTRAL_SIDE_GROUP_WIDTH = CARD_WIDTH + GROUP_BOX_PADDING_X * 2;
const SIDE_AREA_OUTER_INSET_X = 12;
const SIDE_AREA_CENTER_GAP_X = 32;
const CENTRAL_AREA_TARGET_RATIO = 0.3;
const DIRECT_USEFUL_LEFT = DIRECT_FRAME_LEFT + SIDE_AREA_OUTER_INSET_X;
const DIRECT_USEFUL_RIGHT = DIRECT_FRAME_RIGHT - SIDE_AREA_OUTER_INSET_X;
const DIRECT_AREA_CONTENT_WIDTH = DIRECT_USEFUL_RIGHT - DIRECT_USEFUL_LEFT - SIDE_AREA_CENTER_GAP_X * 2;
const CENTRAL_AREA_WIDTH = DIRECT_AREA_CONTENT_WIDTH * CENTRAL_AREA_TARGET_RATIO;
const SIDE_AREA_WIDTH = (DIRECT_AREA_CONTENT_WIDTH - CENTRAL_AREA_WIDTH) / 2;
const PATERNAL_SIDE_AREA_LEFT = DIRECT_USEFUL_LEFT;
const PATERNAL_SIDE_AREA_RIGHT = PATERNAL_SIDE_AREA_LEFT + SIDE_AREA_WIDTH;
const MATERNAL_SIDE_AREA_RIGHT = DIRECT_USEFUL_RIGHT;
const MATERNAL_SIDE_AREA_LEFT = MATERNAL_SIDE_AREA_RIGHT - SIDE_AREA_WIDTH;
const CENTRAL_LEFT_BOUNDARY = PATERNAL_SIDE_AREA_RIGHT + SIDE_AREA_CENTER_GAP_X;
const CENTRAL_RIGHT_BOUNDARY = MATERNAL_SIDE_AREA_LEFT - SIDE_AREA_CENTER_GAP_X;
const FATHER_GROUP_CENTER_X = CENTRAL_LEFT_BOUNDARY + CENTRAL_SIDE_GROUP_WIDTH / 2;
const MOTHER_GROUP_CENTER_X = CENTRAL_RIGHT_BOUNDARY - CENTRAL_SIDE_GROUP_WIDTH / 2;
const PATERNAL_LANE_LEFT = PATERNAL_SIDE_AREA_LEFT;
const PATERNAL_LANE_RIGHT = PATERNAL_SIDE_AREA_RIGHT;
const MATERNAL_LANE_LEFT = MATERNAL_SIDE_AREA_LEFT;
const MATERNAL_LANE_RIGHT = MATERNAL_SIDE_AREA_RIGHT;
const SIDE_LANE_WIDTH = Math.min(
  PATERNAL_LANE_RIGHT - PATERNAL_LANE_LEFT,
  MATERNAL_LANE_RIGHT - MATERNAL_LANE_LEFT
);
const SIDE_GROUP_COLUMNS = 4;
const SIDE_COLLATERAL_MIN_COLUMNS = 2;
const ANCESTOR_GROUP_COLUMNS = 2;
const STANDARD_GROUP_CARD_WIDTH = 400;
const STANDARD_GROUP_CARD_HEIGHT = DIRECT_FAMILY_TOKENS.CARD_HEIGHT;
const SIDE_ANCESTOR_CARD_WIDTH = STANDARD_GROUP_CARD_WIDTH;
const SIDE_ANCESTOR_CARD_HEIGHT = 160;
const SIDE_COLLATERAL_CARD_WIDTH = 370;
const SIDE_COLLATERAL_CARD_HEIGHT = 142;
const SIDE_COLLATERAL_CARD_SCALE_STEP = 0.04;
const SIDE_COLLATERAL_CARD_MAX_SCALE = 1.48;
const SIDE_PARENT_CARD_WIDTH = STANDARD_GROUP_CARD_WIDTH;
const SIDE_PARENT_CARD_HEIGHT = 160;
const CENTRAL_PARENT_GROUP_Y = CENTRAL_Y - CENTRAL_PARENT_GAP - SIDE_PARENT_CARD_HEIGHT;
const LOWER_CARD_WIDTH = 400;
const LOWER_CARD_HEIGHT = 120;
const SIDE_COLUMN_GAP = 16;
const SIDE_ROW_GAP = 12;
const ANCESTOR_COLUMN_GAP = 52;
const ANCESTOR_ROW_GAP = 14;
const IN_GROUP_SIBLING_COLUMN_GAP = 18;
const IN_GROUP_SIBLING_ROW_GAP = 12;
const MARRIAGE_NODE_SIZE = 40;
const SIDE_GROUP_EXTRA_INNER_SPACE = 0;
const SIDE_GROUP_WIDTH =
  SIDE_GROUP_COLUMNS * SIDE_COLLATERAL_CARD_WIDTH +
  Math.max(0, SIDE_GROUP_COLUMNS - 1) * SIDE_COLUMN_GAP +
  GROUP_BOX_PADDING_X * 2 +
  SIDE_GROUP_EXTRA_INNER_SPACE;
const ANCESTOR_GROUP_WIDTH =
  ANCESTOR_GROUP_COLUMNS * SIDE_ANCESTOR_CARD_WIDTH +
  Math.max(0, ANCESTOR_GROUP_COLUMNS - 1) * ANCESTOR_COLUMN_GAP +
  GROUP_BOX_PADDING_X * 2;

const PATERNAL_GROUP_LEFT_X = PATERNAL_LANE_LEFT;
const PATERNAL_GROUP_RIGHT_X = PATERNAL_LANE_RIGHT;
const MATERNAL_GROUP_LEFT_X = MATERNAL_LANE_LEFT;
const MATERNAL_GROUP_RIGHT_X = MATERNAL_LANE_RIGHT;
const PATERNAL_GROUP_LANE_WIDTH = PATERNAL_GROUP_RIGHT_X - PATERNAL_GROUP_LEFT_X;
const MATERNAL_GROUP_LANE_WIDTH = MATERNAL_GROUP_RIGHT_X - MATERNAL_GROUP_LEFT_X;
const PATERNAL_CENTER_X = PATERNAL_GROUP_LEFT_X + PATERNAL_GROUP_LANE_WIDTH / 2;
const MATERNAL_CENTER_X = MATERNAL_GROUP_LEFT_X + MATERNAL_GROUP_LANE_WIDTH / 2;
const LOWER_GROUP_Y = CENTRAL_BASE_Y + CENTRAL_LOWER_REFERENCE_HEIGHT + CENTRAL_LOWER_GROUP_GAP;
const LOWER_LANE_WIDTH = 860;
const LOWER_GROUP_GAP = 10;
const LOWER_LEFT_GROUP_CENTER_X = FATHER_GROUP_CENTER_X;
const LOWER_RIGHT_GROUP_CENTER_X = MOTHER_GROUP_CENTER_X;
const DIRECT_STRUCTURAL_EDGE_STYLE = {
  stroke: DIRECT_FAMILY_TOKENS.EDGE_STROKE,
  strokeWidth: 3,
  opacity: DIRECT_FAMILY_TOKENS.EDGE_OPACITY,
};
const DIRECT_HIGHLIGHT_EDGE_STROKE_WIDTH = DIRECT_STRUCTURAL_EDGE_STYLE.strokeWidth;

const PLACEHOLDER_REST_OF_FILE = false;
