-- =====================================================
-- SQL OPERACIONAL NEUTRALIZADO — CLEANUP TEST USER
-- =====================================================
--
-- Este arquivo continha um roteiro manual de limpeza para um usuario de teste
-- especifico. Ele foi mantido apenas como marcador historico/preventivo para
-- evitar execucao acidental e para preservar rastreabilidade pelo historico do Git.
--
-- Nao execute este arquivo no Supabase SQL Editor.
-- Nao use este arquivo como migration.
-- Nao use este arquivo como roteiro atual de limpeza de dados.
-- Nao manter UUIDs, e-mails, nomes ou dados reais em scripts versionados.
--
-- Fonte oficial do schema:
--   supabase/migrations/
--
-- Documentacao relacionada:
--   docs/historico/SQLS_LEGADOS.md
--   docs/operacao/MIGRATIONS_SUPABASE.md
--   docs/operacao/STORAGE_MAINTENANCE.md
--
-- Se uma limpeza operacional for necessaria, crie um script novo fora do
-- versionamento ou uma rotina revisada com:
--   - escopo explicito;
--   - dry-run;
--   - backup quando houver dados compartilhados ou producao;
--   - projeto Supabase confirmado;
--   - autorizacao explicita;
--   - ausencia de service role, tokens ou dados pessoais no repositorio.
--
-- Este arquivo nao deve conter SELECT operacional, INSERT, UPDATE, DELETE,
-- CREATE, ALTER, DROP, COMMIT, ROLLBACK ou identificadores reais.
-- =====================================================
